# Site settings
title: Alex O'Callaghan
header-img: /img/sky-lights-space-dark.jpg
email: aocallaghan@outlook.com
description: "Personal website, portfolio, and blog of software developer Alex O'Callaghan"
baseurl: ""
url: "//alexocallaghan.com"
secureurl: "https://alexocallaghan.com"
twitter_username: alexocallaghan
github_username:  awocallaghan
facebook_username:

# Custom collections
collections:
  projects:
    output: true
    permalink: /projects/:title

# Featured projects
featuredProjects:
  - 'student-video-analytics'
  - 'maths-problems'
  - 'footyfeeds'

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Build settings
plugins: [
  'jekyll-paginate'
]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
sass:
  style: compressed
exclude: [
  "Gemfile"
  "LICENSE",
  "node_modules",
  "Gulpfile.js",
  "Gulp.config.json",
  "package.json",
  "README.md",
  ".babelrc",
  ".gitignore",
  "js/vendor",
  "js/site",
  "js/maths-problems/*",
  "js/projects/*"
]