# Site settings
title: Alex O'Callaghan
header-img: img/home-bg.jpg
email: aocallaghan@outlook.com
description: "Personal website & blog of Alex O'Callaghan"
baseurl: ""
url: "http://alexocallaghan.com"
twitter_username: alexocallaghan
github_username:  awocallaghan
facebook_username:

# Build settings
gems: ['jekyll-paginate']
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
