# Site settings
title: Alex O'Callaghan
header-img: /img/sky-lights-space-dark.jpg
email: aocallaghan@outlook.com
description: "Personal website, portfolio, and blog of software developer Alex O'Callaghan"
baseurl: ""
url: "http://alexocallaghan.com"
twitter_username: alexocallaghan
github_username:  awocallaghan
facebook_username:

# Custom collections
collections:
  projects:
    output: true
    permalink: /projects/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Build settings
gems: ['jekyll-paginate']
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["LICENSE","node_modules","Gruntfile.js","Gulpfile.js","package.json","README.md",".babelrc",".gitignore","less","css/vendor","css/site","js/vendor","js/site","js/maths-problems"]
